package rippler

// ReportPrinter is an interface for printing reports generated by the rippler tool.
type ReportPrinter interface {
	// Print outputs the report in a specific format.
	Print(report *Report) error
}

// ReportPrinterFunc is a function type that implements the ReportPrinter interface.
type ReportPrinterFunc func(report *Report) error

// Print calls the ReportPrinterFunc with the provided report.
func (f ReportPrinterFunc) Print(report *Report) error {
	return f(report)
}
